version: "3.6"
services:
  tg_bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: ./docker/tg_bot/Dockerfile
    environment:
      TG_BOT_TOKEN: ''
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
  redis_db:
    image: redis
    container_name: redis_db
  postgres_db:
    image: postgres:14.2-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0455"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data